repos:
-   repo: https://github.com/keith/pre-commit-buildifier
    rev: 10.1.0
    hooks:
    -   id: buildifier
    -   id: buildifier-lint
-   repo: local
    hooks:
    -   id: swift-format
        name: swift-format
        entry: ./format.sh
        language: system
        pass_filenames: false
        always_run: true
